export const BUS_TYPES = {
  AC_SLEEPER: "AC_SLEEPER",
  NON_AC_SLEEPER: "NON_AC_SLEEPER",
  AC_SEATER: "AC_SEATER",
  NON_AC_SEATER: "NON_AC_SEATER",
};

export const SEAT_TYPES = {
  WINDOW: "WINDOW",
  MIDDLE: "MIDDLE",
  AISLE: "AISLE",
  SLEEPER: "SLEEPER",
};

export const SEAT_STATUS = {
  AVAILABLE: "AVAILABLE",
  BOOKED: "BOOKED",
};

export const BOOKING_STATUS = {
  BOOKED: "BOOKED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
};

export const PAYMENT_METHODS = {
  UPI: "UPI",
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  NET_BANKING: "NET_BANKING",
  CASH: "CASH",
};

export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};